name:                android-translation-helper
version:             0.1.0.0
github:              "sigrlami/android-translation-helper"
license:             BSD3
author:              "Sergey Bushnyak"
maintainer:          "sergey.bushnyak@sigrlami.eu"
copyright:           "2020, Sergey Bushnyak"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sigrlami/android-translation-helper#readme>

dependencies:
- base >= 4.7 && < 5
- cassava
- xeno
- text
- bytestring
- time
- directory
- optparse-applicative

library:
  source-dirs: src

executables:
  ath:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - android-translation-helper

tests:
  ath-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - android-translation-helper
